package com.mycompany.incidents.otherResources;

public enum HomologationTypeEnum {
    ALL,
    APIGATEWAY_PRODUCT_TYPE_CODE_FROM_OFFERING_TYPE_GW,
    COBERTURA_GW,
    COVERAGE_FROM_OFFERING_COVERAGE_ARTICLE_GW,
    GARANTIA_SUBGARANTIA_EMPRESARIAL_GW,
    LINE_FROM_OFFERING_TYPE_GW,
    LOSS_CAUSE_FROM_SERVICES_GW,
    LOSS_TYPE_FROM_LINE_SUBLINE_GW,
    OFFERING_TYPE_FROM_LINE_SUBLINE_GW,
    POLICY_TYPE_FROM_LINE_SUBLINE_GW,
    REINSURANCECONTRACT_FROM_OFFERING_COVERAGE_GW,
    TERMINO_GW
}
