package com.mycompany.incidents.otherResources;

public enum HomologationTypeEnum { 
  ALL, 
  COBERTURA_GW,
  TERMINO_GW,
  LOSS_CAUSE_FROM_SERVICES_GW,
  OFFERING_TYPE_FROM_LINE_SUBLINE_GW,
  POLICY_TYPE_FROM_LINE_SUBLINE_GW,
  LOSS_TYPE_FROM_LINE_SUBLINE_GW,
  COVERAGE_FROM_OFFERING_COVERAGE_ARTICLE_GW
}
