/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.incidents.panels;

import com.mycompany.incidents.otherResources.IncidentsUtil;
import com.mycompany.incidents.panels.modelGW.DialogHelp;

/**
 *
 * @author santvamu
 */
public class ClosuresPanel extends javax.swing.JPanel {

  /**
   * Creates new form Closures
   */
  public ClosuresPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnImport2 = new javax.swing.JButton();
    btnShowQuery1 = new javax.swing.JButton();
    btnImport3 = new javax.swing.JButton();
    btnShowQuery2 = new javax.swing.JButton();
    btnImport4 = new javax.swing.JButton();
    btnShowQuery3 = new javax.swing.JButton();
    btnShowQuery4 = new javax.swing.JButton();
    btnConsultasCierre = new javax.swing.JButton();
    btnConsutasPoliza = new javax.swing.JButton();

    btnImport2.setText("CIERRE FINANCIERO");
    btnImport2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnImport2ActionPerformed(evt);
      }
    });

    btnShowQuery1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interrogation.png"))); // NOI18N
    btnShowQuery1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowQuery1ActionPerformed(evt);
      }
    });

    btnImport3.setText("CIERRE REASEGURO");
    btnImport3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnImport3ActionPerformed(evt);
      }
    });

    btnShowQuery2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interrogation.png"))); // NOI18N
    btnShowQuery2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowQuery2ActionPerformed(evt);
      }
    });

    btnImport4.setText("CIERRE COASEGURO");
    btnImport4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnImport4ActionPerformed(evt);
      }
    });

    btnShowQuery3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interrogation.png"))); // NOI18N
    btnShowQuery3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowQuery3ActionPerformed(evt);
      }
    });

    btnShowQuery4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interrogation.png"))); // NOI18N
    btnShowQuery4.setText("Como exportar hoja Excel");
    btnShowQuery4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowQuery4ActionPerformed(evt);
      }
    });

    btnConsultasCierre.setText("CONSULTAS CIERRE");
    btnConsultasCierre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultasCierreActionPerformed(evt);
      }
    });

    btnConsutasPoliza.setText("CONSULTAS POLIZA");
    btnConsutasPoliza.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsutasPolizaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(btnConsultasCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnShowQuery4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
          .addComponent(btnConsutasPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(btnImport2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnImport3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnImport4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnShowQuery2)
              .addComponent(btnShowQuery3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnShowQuery1))))
        .addContainerGap(54, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnShowQuery4)
        .addGap(5, 5, 5)
        .addComponent(btnConsultasCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnConsutasPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnImport2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnShowQuery1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnImport3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnShowQuery2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnImport4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnShowQuery3))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnImport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport2ActionPerformed
    DialogFinancialClosure dialog = new DialogFinancialClosure(null,true);
    dialog.setVisible(true);
  }//GEN-LAST:event_btnImport2ActionPerformed

  private void btnShowQuery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQuery1ActionPerformed
    DialogHelp dialog = new DialogHelp(null,true);
		dialog.setTextContent(IncidentsUtil.getText("CierreFinancieroAyuda"));
    dialog.setVisible(true);
  }//GEN-LAST:event_btnShowQuery1ActionPerformed

  private void btnImport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport3ActionPerformed
    DialogReinsuranceClosure dialog = new DialogReinsuranceClosure(null,true);    
    dialog.setVisible(true);
  }//GEN-LAST:event_btnImport3ActionPerformed

  private void btnShowQuery2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQuery2ActionPerformed
    DialogHelp dialog = new DialogHelp(null,true);
    dialog.setTextContent(IncidentsUtil.getText("CierreReaseguroAyuda"));    
    dialog.setVisible(true);
  }//GEN-LAST:event_btnShowQuery2ActionPerformed

  private void btnImport4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport4ActionPerformed
    DialogCoinsuranceClosure dialog = new DialogCoinsuranceClosure(null,true);    
    dialog.setVisible(true);
  }//GEN-LAST:event_btnImport4ActionPerformed

  private void btnShowQuery3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQuery3ActionPerformed
    
    DialogHelp dialog = new DialogHelp(null,true);
    dialog.setTextContent(IncidentsUtil.getText("CierreCoaseguroAyuda"));
    dialog.setVisible(true);    
    
  }//GEN-LAST:event_btnShowQuery3ActionPerformed

  private void btnShowQuery4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQuery4ActionPerformed
    DialogHelp dialog = new DialogHelp(null,true);    
    dialog.setTextContent(IncidentsUtil.getText("ExcelExportHelp"));
    dialog.setVisible(true);    
  }//GEN-LAST:event_btnShowQuery4ActionPerformed

  private void btnConsultasCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasCierreActionPerformed
    DialogGenerateClosureQuery dialog = new DialogGenerateClosureQuery(null,true);
		dialog.setVisible(true);  
  }//GEN-LAST:event_btnConsultasCierreActionPerformed

  private void btnConsutasPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutasPolizaActionPerformed
    DialogGeneratePolicyQuery dialog = new DialogGeneratePolicyQuery(null,true);
		dialog.setVisible(true);
  }//GEN-LAST:event_btnConsutasPolizaActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConsultasCierre;
  private javax.swing.JButton btnConsutasPoliza;
  private javax.swing.JButton btnImport2;
  private javax.swing.JButton btnImport3;
  private javax.swing.JButton btnImport4;
  private javax.swing.JButton btnShowQuery1;
  private javax.swing.JButton btnShowQuery2;
  private javax.swing.JButton btnShowQuery3;
  private javax.swing.JButton btnShowQuery4;
  // End of variables declaration//GEN-END:variables
}
