/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.incidents.panels;

import com.mycompany.incidents.otherResources.ClosureQueryTypeEnum;
import com.mycompany.incidents.otherResources.IncidentsUtil;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author santvamu
 */
public class DialogGenerateClosureQuery extends javax.swing.JDialog {

	String intialDay = "";
	String intialYear = "";
	String intialMonth = "";
	String endDay = "";
	String endYear = "";
	String endMonth = "";

	/**
	 * Creates new form DialogGenerateClosureQuery
	 */
	public DialogGenerateClosureQuery(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public DefaultComboBoxModel<String> getClosuresQueryTypes() {
		DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
		ClosureQueryTypeEnum[] values = ClosureQueryTypeEnum.values();
		for (ClosureQueryTypeEnum value : values) {
			comboModel.addElement(value.toString());
		}
		return comboModel;
	}

	private void printInOutputText(String textToAdd) {
		outputTxt.setText(outputTxt.getText() + textToAdd);
		outputTxt.setCaretPosition(outputTxt.getDocument().getLength());
	}	

	private void generateCierreFinancieroGastos() {
		String out = IncidentsUtil.getText("CierreFinancieroGastos");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);
		
	}

	private void generateCierreFinancieroPagos() {
		String out = IncidentsUtil.getText("CierreFinancieroPagos");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void generateCierreFinancieroReservas() {
		String out = IncidentsUtil.getText("CierreFinancieroReservas");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void generateCierreFinancieroSalvamentos() {
		String out = IncidentsUtil.getText("CierreFinancieroSalvamentos");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);
	}

	private void generateCierreReaseguroCuentas() {
		String out = IncidentsUtil.getText("CierreReaseguroCuentas");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
		
	}

	private void generateCierreReaseguroGW() {
		String out = IncidentsUtil.getText("CierreReaseguroGW");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);						
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void generateCierreReaseguroValidaciones() {
		
		String out = IncidentsUtil.getText("CierreReaseguroValidaciones");
		out = out.replaceAll("INITIAL_DATE",intialYear + intialMonth + intialDay);						
		out = out.replaceAll("END_DATE",endYear + endMonth + endDay);	
		out = out.replaceAll("INITIAL_DATE_YM",intialYear + intialMonth);			
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void configureDate() {
		try {
			SimpleDateFormat sdf    = new SimpleDateFormat("dd-MM-YYYY");
			String parseInitialDate = sdf.format(initialDateChooser.getDate());
			String parseEndDate     = sdf.format(endDateChooser.getDate());			
			String[] splitInitialDate = parseInitialDate.split("-");
			String[] splitEndDate = parseEndDate.split("-");
			intialDay   = splitInitialDate[0];
			intialYear  = splitInitialDate[2];
			intialMonth = splitInitialDate[1];
			endDay      = splitEndDate[0];			
			endMonth    = splitEndDate[1];
			endYear     = splitEndDate[2];

		} catch (Exception e) {
			outputTxt.setText("El formato de las fechas no es correcto");
		  outputTxt.setCaretPosition(0);
			//IncidentsUtil.printStackTrace(e,outputTxt);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    comboQueryType = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    outputTxt = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    initialDateChooser = new com.toedter.calendar.JDateChooser();
    endDateChooser = new com.toedter.calendar.JDateChooser();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("GENERADOR DE CONSULTAS PARA CIERRES");

    jLabel1.setText("Fecha Inicio(dd-MM-YYYY)");

    jLabel3.setText("Fecha Fin (dd-MM-YYYY)");

    comboQueryType.setModel(getClosuresQueryTypes());

    jLabel4.setText("Tipo de query");

    outputTxt.setColumns(20);
    outputTxt.setRows(5);
    jScrollPane1.setViewportView(outputTxt);

    jButton1.setText("Generar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    initialDateChooser.setDateFormatString("dd-MM-yyyy");

    endDateChooser.setDateFormatString("dd-MM-yyyy");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(comboQueryType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(initialDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboQueryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(initialDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        .addContainerGap())
    );

    setSize(new java.awt.Dimension(546, 441));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		if(comboQueryType.getSelectedIndex()==-1){
			outputTxt.setText("No se ha seleccionado el tipo de query");
		  outputTxt.setCaretPosition(0);
			return;
		}
		configureDate();
		ClosureQueryTypeEnum queryType = ClosureQueryTypeEnum.valueOf(
						                         comboQueryType.getSelectedItem().toString());
		switch (queryType) {
			case CierreFinancieroGastos:
				generateCierreFinancieroGastos();
				break;
			case CierreFinancieroPagos:
				generateCierreFinancieroPagos();
				break;
			case CierreFinancieroReservas:
				generateCierreFinancieroReservas();
				break;
			case CierreFinancieroSalvamentos:
				generateCierreFinancieroSalvamentos();
				break;
			case CierreReaseguroCuentas:
				generateCierreReaseguroCuentas();
				break;
			case CierreReaseguroGW:
				generateCierreReaseguroGW();
				break;
			case CierreReaseguroValidaciones:
				generateCierreReaseguroValidaciones();
				break;
		}
  }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogGenerateClosureQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogGenerateClosureQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogGenerateClosureQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogGenerateClosureQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DialogGenerateClosureQuery dialog = new DialogGenerateClosureQuery(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> comboQueryType;
  private com.toedter.calendar.JDateChooser endDateChooser;
  private com.toedter.calendar.JDateChooser initialDateChooser;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea outputTxt;
  // End of variables declaration//GEN-END:variables
}
