/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.incidents.panels;

import com.mycompany.incidents.otherResources.IncidentsUtil;
import com.mycompany.incidents.otherResources.PolicyQueryTypeEnum;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author santvamu
 */
public class DialogGeneratePolicyQuery extends javax.swing.JDialog {

	String aDay = "";
	String aYear = "";
	String aMonth = "";

	/**
	 * Creates new form DialogGeneratePolicyQuery
	 */
	public DialogGeneratePolicyQuery(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public DefaultComboBoxModel<String> getPolicyQueryTypes() {
		DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
		PolicyQueryTypeEnum[] values = PolicyQueryTypeEnum.values();
		for (PolicyQueryTypeEnum value : values) {
			comboModel.addElement(value.toString());
		}
		return comboModel;
	}

	private void printInOutputText(String textToAdd) {
		outputTxt.setText(outputTxt.getText() + textToAdd);
		outputTxt.setCaretPosition(outputTxt.getDocument().getLength());
	}

	private void generateQueryBeneficiarios() {
		String out = IncidentsUtil.getText("ConsultaPolizaBeneficiarios");
		out = out.replaceAll("NUM_POLIZA",txtPolicyNumber.getText().trim());
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void generateQueryCoaseguradores() {
		String out = IncidentsUtil.getText("ConsultaPolizaCoaseguradores");
		out = out.replaceAll("NUM_POLIZA",txtPolicyNumber.getText().trim());		
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		out = out.replaceAll("INITIAL_DATE",aYear + "/" + aMonth + "/" + aDay);
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);
	}

	private void generateCommonQueries() {
		String out = IncidentsUtil.getText("ConsultaPolizaConsultasComunes");
		out = out.replaceAll("NUM_POLIZA",txtPolicyNumber.getText().trim());		
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		out = out.replaceAll("INITIAL_DATE",aYear + "/" + aMonth + "/" + aDay);
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);
	}

	private void generateQueryCoberturas() {
		String out = IncidentsUtil.getText("ConsultaPolizaCobertura");
		out = out.replaceAll("NUM_POLIZA",txtPolicyNumber.getText().trim());		
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		out = out.replaceAll("INITIAL_DATE",aYear + "-" + aMonth + "-" + aDay);
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);		
	}

	private void generateQueryDirecciones() {
		String out = IncidentsUtil.getText("ConsultaPolizaDirecciones");
		out = out.replaceAll("TIPO_NUM_IDENTIFICACION",txtIdentification.getText().trim());		
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);				
	}

	private void generateQueryTerminos() {
		String out = IncidentsUtil.getText("ConsultaPolizaTerminos");
		out = out.replaceAll("NUM_POLIZA",txtPolicyNumber.getText().trim());		
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		out = out.replaceAll("INITIAL_DATE",aYear + "-" + aMonth + "-" + aDay);
		out = out.replaceAll("NUM_RIESGO",txtRiskNumber.getText().trim());
		out = out.replaceAll("HOMOLOGACION_COBERTURA",txtHomologation.getText().trim());
		outputTxt.setText(out);
		outputTxt.setCaretPosition(0);
	}

	private void configureDate() {
		try {
			SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
			String parseInitialDate = sdf.format(initialDateChooser.getDate());
			String[] splitInitialDate = parseInitialDate.split("-");
			aDay = splitInitialDate[0];
			aYear = splitInitialDate[2];
			aMonth = splitInitialDate[1];
		} catch (Exception e) {
			outputTxt.setText("El formato de las fechas no es correcto");
			outputTxt.setCaretPosition(0);
			//IncidentsUtil.printStackTrace(e,outputTxt);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    comboQueryType = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    outputTxt = new javax.swing.JTextArea();
    btnGenerteQuery = new javax.swing.JButton();
    initialDateChooser = new com.toedter.calendar.JDateChooser();
    jLabel2 = new javax.swing.JLabel();
    txtIdentification = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtRiskNumber = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    txtPolicyNumber = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtHomologation = new javax.swing.JTextField();
    btnClear = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("GENERADOR DE CONSULTAS DE POLIZA");

    jLabel1.setText("Fecha (dd-MM-YYYY)");

    comboQueryType.setModel(getPolicyQueryTypes());
    comboQueryType.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        comboQueryTypeItemStateChanged(evt);
      }
    });
    comboQueryType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        comboQueryTypePropertyChange(evt);
      }
    });

    jLabel4.setText("Tipo de query");

    outputTxt.setColumns(20);
    outputTxt.setRows(5);
    jScrollPane1.setViewportView(outputTxt);

    btnGenerteQuery.setText("Generar");
    btnGenerteQuery.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGenerteQueryActionPerformed(evt);
      }
    });

    initialDateChooser.setDateFormatString("dd-MM-yyyy");

    jLabel2.setText("Póliza");

    jLabel3.setText("Riesgo");

    jLabel5.setText("Tipo+ Num Identificación");

    txtPolicyNumber.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPolicyNumberActionPerformed(evt);
      }
    });

    jLabel6.setText("Homologación cobertura");

    btnClear.setText("Limpiar");
    btnClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnClearActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(txtHomologation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnGenerteQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(txtRiskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(initialDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(txtIdentification)
                  .addComponent(comboQueryType, 0, 198, Short.MAX_VALUE))))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(initialDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(comboQueryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2)
              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtRiskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtHomologation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(btnClear)
          .addComponent(btnGenerteQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        .addContainerGap())
    );

    setSize(new java.awt.Dimension(638, 400));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnGenerteQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerteQueryActionPerformed
		if (comboQueryType.getSelectedIndex() == -1) {
			outputTxt.setText("No se ha seleccionado el tipo de query");
			outputTxt.setCaretPosition(0);
			return;
		}
		configureDate();
		PolicyQueryTypeEnum queryType = PolicyQueryTypeEnum.valueOf(
						comboQueryType.getSelectedItem().toString());
		switch (queryType) {
			case Beneficiarios:
				generateQueryBeneficiarios();
				break;
			case Coaseguradores:
				generateQueryCoaseguradores();
				break;
			case Coberturas:
				generateQueryCoberturas();
				break;
			case Direcciones:
				generateQueryDirecciones();
				break;
			case Terminos:
				generateQueryTerminos();
				break;
			case ConsultasComunes:
				generateCommonQueries();
				break;
		}
  }//GEN-LAST:event_btnGenerteQueryActionPerformed

  private void comboQueryTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboQueryTypeItemStateChanged

  }//GEN-LAST:event_comboQueryTypeItemStateChanged

  private void txtPolicyNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPolicyNumberActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_txtPolicyNumberActionPerformed

  private void comboQueryTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboQueryTypePropertyChange
		txtHomologation.setEnabled(false);
		txtIdentification.setEnabled(false);
		txtPolicyNumber.setEnabled(false);
		txtRiskNumber.setEnabled(false);
		btnGenerteQuery.setEnabled(false);
		initialDateChooser.setEnabled(false);
		if (comboQueryType.getSelectedIndex() != -1) {
			PolicyQueryTypeEnum queryType = PolicyQueryTypeEnum.valueOf(
							comboQueryType.getSelectedItem().toString());
			switch (queryType) {
				case Beneficiarios:
					txtPolicyNumber.setEnabled(true);
					txtRiskNumber.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
				case Coaseguradores:
					initialDateChooser.setEnabled(true);
					txtPolicyNumber.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
				case Coberturas:
					initialDateChooser.setEnabled(true);
					txtPolicyNumber.setEnabled(true);
					txtRiskNumber.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
				case Direcciones:
					txtIdentification.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
				case Terminos:
					txtHomologation.setEnabled(true);
					initialDateChooser.setEnabled(true);
					txtPolicyNumber.setEnabled(true);
					txtRiskNumber.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
				case ConsultasComunes:
					initialDateChooser.setEnabled(true);
					txtPolicyNumber.setEnabled(true);
					txtRiskNumber.setEnabled(true);
					btnGenerteQuery.setEnabled(true);
					break;
			}
		}
  }//GEN-LAST:event_comboQueryTypePropertyChange

  private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

		txtHomologation.setText("");
		txtIdentification.setText("");
		txtPolicyNumber.setText("");
		txtRiskNumber.setText("");
		outputTxt.setText("");

  }//GEN-LAST:event_btnClearActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogGeneratePolicyQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogGeneratePolicyQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogGeneratePolicyQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogGeneratePolicyQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DialogGeneratePolicyQuery dialog = new DialogGeneratePolicyQuery(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClear;
  private javax.swing.JButton btnGenerteQuery;
  private javax.swing.JComboBox<String> comboQueryType;
  private com.toedter.calendar.JDateChooser initialDateChooser;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea outputTxt;
  private javax.swing.JTextField txtHomologation;
  private javax.swing.JTextField txtIdentification;
  private javax.swing.JTextField txtPolicyNumber;
  private javax.swing.JTextField txtRiskNumber;
  // End of variables declaration//GEN-END:variables
}
